title: "Jaurice O'Connor"
logo: logo.png
author: "Jaurice O'Connor"
copyright: "2026"

execute:
  execute_notebooks: off

html:
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false
  extra_footer: ""

sphinx:
  config:
    html_static_path:
      - _static
    templates_path:
      - _templates
    html_css_files:
      - custom.css

exclude_patterns:
  - "_build"
  - ".venv_energy"
  - "archive_unused"
  - "energy_pricing_model copy"
  - "**.ipynb_checkpoints"
  - "**/.DS_Store"
