title: Jaurice Research Notes
author: Jaurice O'Connor


execute:
  execute_notebooks: force

repository:
  url: https://github.com/yourusername/jaurice-notes-book
  branch: main

html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false
  use_download_button: false
  home_page_in_navbar: false
  extra_navbar: ""
  extra_footer: ""

  theme:
    name: sphinx_book_theme
    options:
      default_mode: light

sphinx:
  config:
    html_css_files:
      - custom.css
      

