title: Jaurice Research Notes
author: Jaurice O'Connor
logo: assets/sidebar-logo.png
execute:
  execute_notebooks: force
repository:
  url: https://github.com/jauricestudios/jaurice-market-notes
  branch: main
html:
  theme_options:
    use_repository_button: true
    use_download_button: true
    use_fullscreen_button: true
  extra_css:
  - custom.css
xtra_css:
- _static/custom.css
theme:
  name: sphinx_book_theme
  options:
    default_mode: dark
sphinx:
  config:
    html_static_path:
    - _static
    html_css_files:
    - custom.css
    html_title: Jaurice O'Connor | Risk Analytics Portfolio
    html_theme_options:
      default_mode: light
      navbar_start:
      - navbar-logo
